import io
from fpdf import FPDF

def sanitize_text(text: str) -> str:
    """Replaces non-latin1 unicode characters with ASCII equivalents to prevent FPDF errors."""
    if not isinstance(text, str):
        text = str(text)
    replacements = {
        "—": "-",
        "–": "-",
        "“": '"',
        "”": '"',
        "‘": "'",
        "’": "'",
        "•": "*",
        "…": "...",
    }
    for orig, repl in replacements.items():
        text = text.replace(orig, repl)
    return text.encode("latin-1", errors="replace").decode("latin-1")

class DossierPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(220, 38, 38)  # Crimson Header
        self.cell(0, 10, sanitize_text("VIGIL FRAUD INVESTIGATION COMMAND CENTER"), border=0, new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, sanitize_text("CONFIDENTIAL JUDICIAL FRAUD DOSSIER REPORT"), border=0, new_x="LMARGIN", new_y="NEXT", align="C")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, sanitize_text(f"Page {self.page_no()}/{{nb}} - Generated by Vigil AI Governance System"), align="C")

def render_dossier_pdf(dossier_data: dict) -> io.BytesIO:
    """
    Renders a Dossier payload into a downloadable PDF binary stream buffer.
    """
    pdf = DossierPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    tx_id = sanitize_text(str(dossier_data.get("transaction_id", "N/A")))
    score = dossier_data.get("risk_score", 0.0)
    verdict = sanitize_text(str(dossier_data.get("verdict", "PENDING_REVIEW")))
    summary = sanitize_text(str(dossier_data.get("executive_summary", "No summary provided.")))
    
    # Metadata Box
    pdf.set_fill_color(245, 247, 250)
    pdf.rect(10, 30, 190, 28, style="F")
    
    pdf.set_xy(15, 33)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 41, 59)
    pdf.cell(90, 6, sanitize_text(f"Transaction ID: {tx_id}"))
    
    pdf.set_xy(110, 33)
    pdf.set_font("Helvetica", "B", 11)
    if score >= 0.7:
        pdf.set_text_color(220, 38, 38)
    else:
        pdf.set_text_color(22, 163, 74)
    pdf.cell(85, 6, sanitize_text(f"Risk Score: {score:.3f} / 1.000"), align="R")
    
    pdf.set_xy(15, 41)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(71, 85, 105)
    pdf.cell(90, 6, sanitize_text(f"Final Verdict: {verdict}"))
    
    pdf.set_xy(110, 41)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(85, 6, sanitize_text(f"Classification: {dossier_data.get('classification', 'ANALYZED')}"), align="R")
    
    # Reset cursor after absolute metadata positioning
    pdf.set_xy(pdf.l_margin, 65)
    
    # Executive Summary Section
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(15, 23, 42)
    pdf.cell(pdf.epw, 8, sanitize_text("1. Executive Summary"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(51, 65, 85)
    pdf.multi_cell(pdf.epw, 5, summary, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    
    # Prosecution Evidence Section
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(220, 38, 38)
    pdf.cell(pdf.epw, 8, sanitize_text("2. Prosecution Evidence (Incriminating Signals)"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(30, 41, 59)
    
    prosecution_list = dossier_data.get("prosecution_evidence", [])
    if not prosecution_list:
        pdf.cell(pdf.epw, 5, sanitize_text("No major incriminating evidence flagged."), new_x="LMARGIN", new_y="NEXT")
    else:
        for idx, item in enumerate(prosecution_list, 1):
            if isinstance(item, dict):
                title = sanitize_text(item.get("title", item.get("name", "Evidence")))
                detail = sanitize_text(item.get("description", item.get("detail", "")))
                impact = item.get("impact", "")
                text = f"{idx}. {title}: {detail}" if detail else f"{idx}. {title}"
                if impact:
                    text += f" (Impact: +{impact})"
            else:
                text = f"{idx}. {sanitize_text(str(item))}"
            pdf.multi_cell(pdf.epw, 5, text, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    
    # Defense Counter-Evidence Section
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(22, 163, 74)
    pdf.cell(pdf.epw, 8, sanitize_text("3. Defense Counter-Evidence (Mitigating Factors)"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(30, 41, 59)
    
    defense_list = dossier_data.get("defense_evidence", [])
    if not defense_list:
        pdf.cell(pdf.epw, 5, sanitize_text("No defense mitigating factors identified."), new_x="LMARGIN", new_y="NEXT")
    else:
        for idx, item in enumerate(defense_list, 1):
            if isinstance(item, dict):
                title = sanitize_text(item.get("title", item.get("name", "Mitigating Factor")))
                detail = sanitize_text(item.get("description", item.get("detail", "")))
                text = f"{idx}. {title}: {detail}" if detail else f"{idx}. {title}"
            else:
                text = f"{idx}. {sanitize_text(str(item))}"
            pdf.multi_cell(pdf.epw, 5, text, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    
    # Explainability Drivers Section
    drivers = dossier_data.get("explainability_drivers", [])
    if drivers:
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(pdf.epw, 8, sanitize_text("4. CatBoost TreeSHAP Risk Drivers"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9.5)
        for drv in drivers:
            if isinstance(drv, dict):
                feat = sanitize_text(str(drv.get("feature", "Feature")))
                val = str(drv.get("value", ""))
                shap_val = drv.get("shap_value", 0.0)
                line = f"* {feat} (Value: {val}) -> SHAP Impact: {shap_val:+.3f}"
            else:
                line = f"* {sanitize_text(str(drv))}"
            pdf.cell(pdf.epw, 5, line, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    # Output to BytesIO buffer
    pdf_buffer = io.BytesIO()
    pdf_output = pdf.output()
    pdf_buffer.write(pdf_output)
    pdf_buffer.seek(0)
    return pdf_buffer
