import os
import pandas as pd
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split

def train_and_evaluate_catboost():
    print("🤖 Initializing CatBoost Training Pipeline...")
    
    # 1. Load clean transaction data generated by the simulator
    data_path = os.path.join("data", "processed", "raw_clean", "transactions_clean.csv")
    if not os.path.exists(data_path):
        data_path = os.path.join("data", "raw", "transactions.csv")
        
    if not os.path.exists(data_path):
        print("❌ Error: No transaction data found. Run demo_pipeline.py first!")
        return
        
    df = pd.read_csv(data_path)
    print(f"📊 Loaded {len(df)} transactions for training.")
    
    # 2. Ensure target label 'isFraud' exists
    if 'isFraud' not in df.columns:
        df['isFraud'] = 0  # Default fallback if unlabelled
        
    # 3. Select features for training (numeric and categorical)
    feature_cols = ['amount']
    # If categorical columns exist, include them safely
    for col in ['currency', 'location', 'transaction_type']:
        if col in df.columns:
            df[col] = df[col].astype(str)
            feature_cols.append(col)
            
    X = df[feature_cols]
    y = df['isFraud'].astype(int)
    
    # Handle case where all labels might be 0 in a small synthetic batch
    if y.nunique() < 2:
        print("⚠️ Warning: Only one class found in target labels. Injecting dummy fraud flag for training stability...")
        if len(y) > 0:
            y.iloc[0] = 1 # Force at least one positive class
            
    # 4. Split into Train / Validation / Test sets
    X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, random_state=42)
    X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)
    
    # 5. Train CatBoost Model
    print("🚀 Training CatBoost Classifier...")
    cat_features = [col for col in ['currency', 'location', 'transaction_type'] if col in X_train.columns]
    
    model = CatBoostClassifier(iterations=50, learning_rate=0.1, depth=4, verbose=0, auto_class_weights='Balanced')
    model.fit(X_train, y_train, cat_features=cat_features, eval_set=(X_val, y_val))
    
    # 6. Generate Predictions & Probabilities
    val_probs = model.predict_proba(X_val)[:, 1]
    val_preds = model.predict(X_val)
    
    test_probs = model.predict_proba(X_test)[:, 1]
    test_preds = model.predict(X_test)
    
    # 7. Save Required Artifacts to reports/
    reports_dir = "reports"
    os.makedirs(reports_dir, exist_ok=True)
    
    val_report = pd.DataFrame({
        'transaction_id': df.iloc[X_val.index]['transaction_id'] if 'transaction_id' in df.columns else range(len(X_val)),
        'prediction': val_preds,
        'probability': val_probs
    })
    
    test_report = pd.DataFrame({
        'transaction_id': df.iloc[X_test.index]['transaction_id'] if 'transaction_id' in df.columns else range(len(X_test)),
        'prediction': test_preds,
        'probability': test_probs
    })
    
    val_report.to_csv(os.path.join(reports_dir, "catboost_validation_predictions.csv"), index=False)
    test_report.to_csv(os.path.join(reports_dir, "catboost_test_predictions.csv"), index=False)
    
    print("✅ CatBoost training complete! Saved validation and test predictions to reports/")

if __name__ == "__main__":
    train_and_evaluate_catboost()
