"""
Investigation Pydantic Data Models.
Shared schema representing full investigation state for LangGraph orchestration.
"""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field
from schemas.transaction import Transaction, MLPrediction
from schemas.evidence import EvidenceItem, SimilarAttackResult


class FraudPatternResult(BaseModel):
    """Result of evaluating a specific fraud pattern."""

    pattern_name: str = Field(..., description="One of the 7 finalized fraud pattern names")
    detected: bool = Field(..., description="Whether pattern threshold was triggered")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Detection confidence score")
    matched_rules: List[str] = Field(default_factory=list, description="Triggered rule IDs")
    details: Dict[str, Any] = Field(default_factory=dict, description="Pattern specific evidence metadata")


class GraphAnalysisResult(BaseModel):
    """Network topology analysis results from NetworkX graph engine."""

    account_id: str = Field(..., description="Target account ID")
    is_ring_member: bool = Field(False, description="True if account is part of a fraud ring")
    ring_id: Optional[str] = Field(None, description="Identified fraud ring ID")
    hub_score: float = Field(0.0, ge=0.0, le=1.0, description="Network centrality/hub score")
    path_length_to_mule: Optional[int] = Field(None, description="Shortest path length to known mule node")
    suspicious_connections: List[Dict[str, Any]] = Field(default_factory=list, description="Connected entities")


class InvestigationState(BaseModel):
    """Complete state container managed across LangGraph investigation pipeline nodes."""

    case_id: str = Field(..., description="Unique investigation case ID")
    transaction: Transaction = Field(..., description="Target transaction")
    ml_screening: Optional[MLPrediction] = Field(None, description="CatBoost screening result")
    patterns_detected: List[FraudPatternResult] = Field(default_factory=list, description="Triggered patterns")
    graph_result: Optional[GraphAnalysisResult] = Field(None, description="Network graph findings")
    evidences: List[EvidenceItem] = Field(default_factory=list, description="Collected risk indicators")
    counter_evidences: List[EvidenceItem] = Field(default_factory=list, description="Collected counter-evidence")
    similar_attacks: List[SimilarAttackResult] = Field(default_factory=list, description="Vector memory matches")
    risk_score: float = Field(0.0, ge=0.0, le=100.0, description="Composite aggregate risk score (0-100)")
    llm_summary: Optional[str] = Field(None, description="Structured explanation generated by LLM")
    recommended_action: str = Field("HOLD", description="Recommended action: APPROVE, HOLD, ESCALATE, BLOCK")
    status: str = Field("PENDING_REVIEW", description="Pipeline status: INVESTIGATING, PENDING_REVIEW, RESOLVED")
